name: 'Do Not Submit'
description: 'Prevent pull requests from being submitted by failing if changes contain a key word'
inputs:
  keyword:
    description: 'The keyword to search for in the file changes. Must not be empty.'
    required: true
    default: 'DO_NOT_SUBMIT'
  should_fail:
    description: 'Whether the action should fail if the keyword is found. If false, the action will succeed even when the keyword is found.'
    required: false
    default: 'true'
  check_list:
    description: 'A list of files to search for the keyword. If using wildcards, be sure to wrap the list in quotes.'
    required: true
    default: '"*"'
  ignore_list:
    description: 'A list of files to ignore when searching for the keyword'
    required: false
    default: '""' # Default to `""` so the first changed file is not ignored
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Fetch changed files
      id: changed-files
      uses: tj-actions/changed-files@v37
    - name: Check files for ${{ inputs.keyword }}
      id: check-files
      shell: bash
      run: |
        ${{ github.action_path }}/do-not-submit.sh ${{ inputs.keyword }} ${{ inputs.check_list }} ${{ inputs.ignore_list }} ${{ steps.changed-files.outputs.all_changed_files }}
